import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { deriveSalt, intentCommitment, intentPreimage } from "../src/internal/zk.js";

/**
 * Vectors are generated by `cargo test -p nomad-types --test zk_vectors`. The
 * circuit, the Solidity escrow, and this encoder must reproduce every preimage
 * and digest byte for byte.
 */
const VECTORS = JSON.parse(
  readFileSync(new URL("./fixtures/zk_vectors.json", import.meta.url), "utf-8"),
);

describe("zk intent vectors", () => {
  it("matches the pinned relation version", () => {
    expect(VECTORS.relation_version).toBe(2);
  });

  for (const testCase of VECTORS.cases) {
    it(`reproduces ${testCase.name}`, () => {
      const input = testCase.intent.inputs;
      const opening = {
        instanceDomain: input.instance_domain,
        chainId: input.chain_id,
        escrow: input.escrow,
        requestId: input.request_id,
        rowIndex: input.row_index,
        asset: input.asset,
        recipient: input.recipient,
        amount: BigInt(input.amount),
        salt: input.salt,
      };
      expect(intentPreimage(opening)).toBe(testCase.intent.preimage);
      expect(intentCommitment(opening)).toBe(testCase.intent.commitment);
    });
  }
});

describe("deriveSalt", () => {
  const scalar = `0x${"11".repeat(32)}` as const;
  const domain = `0x${"22".repeat(32)}` as const;
  const request = `0x${"33".repeat(32)}` as const;

  it("is deterministic", () => {
    expect(deriveSalt(scalar, domain, request, 0)).toBe(deriveSalt(scalar, domain, request, 0));
  });

  it("separates every input", () => {
    const baseline = deriveSalt(scalar, domain, request, 0);
    expect(deriveSalt(`0x${"44".repeat(32)}`, domain, request, 0)).not.toBe(baseline);
    expect(deriveSalt(scalar, `0x${"44".repeat(32)}`, request, 0)).not.toBe(baseline);
    expect(deriveSalt(scalar, domain, `0x${"44".repeat(32)}`, 0)).not.toBe(baseline);
    expect(deriveSalt(scalar, domain, request, 1)).not.toBe(baseline);
  });
});
